# Description: This is a test workflow for running a Python script on a self-hosted runner
# Don't chain jobs together as any failure in one job will stop the workflow

name: Python test
run-name: python_test
on: 
  pull_request:
  workflow_dispatch:
jobs:
  Preamble:
    runs-on: self-hosted
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }} preamble
      cancel-in-progress: true
    steps:
      - run: pwd
      - run: which python
      - run: conda info --envs
      - name: Set up repo
        uses: actions/checkout@v4
      - run: git status
      - run: echo "${{ github.ref }} | ${{ github.repository }} | ${{ github.event.pull_request.title }}"
      - name: Copy files to working-directory
        run: cp -r ./* /home/exouser/Desktop/blech_clust
      - name: Check files in working-directory
        run: ls -R /home/exouser/Desktop/blech_clust
      - name: Setup params
        run: cp /home/exouser/Desktop/blech_clust/params/_templates/* /home/exouser/Desktop/blech_clust/params
      - name: Check params
        run: for f in $(find /home/exouser/Desktop/blech_clust/params/ -type f); do echo $f; cat $f; done
  Spike-Only:
    runs-on: self-hosted
    needs: Preamble
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }} spike
      cancel-in-progress: true
    steps:
      - name: Prefect SPIKE only test
        shell: bash
        working-directory: /home/exouser/Desktop/blech_clust
        run: python pipeline_testing/prefect_pipeline.py -s 2>&1 |
          tee ~/Desktop/blech_clust/github.log;
          if grep -q "ERROR" ~/Desktop/blech_clust/github.log;
                            then echo "ERROR detected by bash"; exit 1; fi
  EMG-Only:
    runs-on: self-hosted
    needs: Preamble
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }} emg
      cancel-in-progress: true
    steps:
      - name: Prefect EMG only test
        shell: bash
        working-directory: /home/exouser/Desktop/blech_clust
        run: python pipeline_testing/prefect_pipeline.py -e 2>&1 |
          tee ~/Desktop/blech_clust/github.log;
          if grep -q "ERROR" ~/Desktop/blech_clust/github.log;
                            then echo "ERROR detected by bash"; exit 1; fi
  Spike-EMG:
    runs-on: self-hosted
    needs: Preamble
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }} spike+emg
      cancel-in-progress: true
    steps:
      - name: Prefect SPIKE then EMG test
        shell: bash
        working-directory: /home/exouser/Desktop/blech_clust
        run: python pipeline_testing/prefect_pipeline.py --spike-emg 2>&1 |
          tee ~/Desktop/blech_clust/github.log;
          if grep -q "ERROR" ~/Desktop/blech_clust/github.log;
                            then echo "ERROR detected by bash"; exit 1; fi
